// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCategory(arg1) {
  return window['go']['main']['App']['GetCategory'](arg1);
}

export function GetSupportedOutputs(arg1) {
  return window['go']['main']['App']['GetSupportedOutputs'](arg1);
}

export function GetToolStatus() {
  return window['go']['main']['App']['GetToolStatus']();
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectFiles() {
  return window['go']['main']['App']['SelectFiles']();
}

export function StartConversion(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartConversion'](arg1, arg2, arg3, arg4);
}
