// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCategory(arg1:string):Promise<string>;

export function GetSupportedOutputs(arg1:string):Promise<Array<string>>;

export function GetToolStatus():Promise<Record<string, boolean>>;

export function OpenFile(arg1:string):Promise<void>;

export function OpenFolder(arg1:string):Promise<void>;

export function SelectDirectory():Promise<string>;

export function SelectFiles():Promise<Array<string>>;

export function StartConversion(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;
